// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosine_distances
NumericMatrix cosine_distances(NumericMatrix data);
RcppExport SEXP _lloydr_cosine_distances(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_distances(data));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_distances
NumericMatrix euclidean_distances(NumericMatrix data);
RcppExport SEXP _lloydr_euclidean_distances(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_distances(data));
    return rcpp_result_gen;
END_RCPP
}
// gower_distances
NumericMatrix gower_distances(NumericMatrix data);
RcppExport SEXP _lloydr_gower_distances(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(gower_distances(data));
    return rcpp_result_gen;
END_RCPP
}
// manhattan_distances
NumericMatrix manhattan_distances(NumericMatrix data);
RcppExport SEXP _lloydr_manhattan_distances(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(manhattan_distances(data));
    return rcpp_result_gen;
END_RCPP
}
// scale_df
DataFrame scale_df(DataFrame data, LogicalVector is_numeric);
RcppExport SEXP _lloydr_scale_df(SEXP dataSEXP, SEXP is_numericSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_numeric(is_numericSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_df(data, is_numeric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lloydr_cosine_distances", (DL_FUNC) &_lloydr_cosine_distances, 1},
    {"_lloydr_euclidean_distances", (DL_FUNC) &_lloydr_euclidean_distances, 1},
    {"_lloydr_gower_distances", (DL_FUNC) &_lloydr_gower_distances, 1},
    {"_lloydr_manhattan_distances", (DL_FUNC) &_lloydr_manhattan_distances, 1},
    {"_lloydr_scale_df", (DL_FUNC) &_lloydr_scale_df, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lloydr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
