# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_distances <- function(data) {
    .Call('_lloydr_cosine_distances', PACKAGE = 'lloydr', data)
}

euclidean_distances <- function(data) {
    .Call('_lloydr_euclidean_distances', PACKAGE = 'lloydr', data)
}

gower_distances <- function(data) {
    .Call('_lloydr_gower_distances', PACKAGE = 'lloydr', data)
}

manhattan_distances <- function(data) {
    .Call('_lloydr_manhattan_distances', PACKAGE = 'lloydr', data)
}

scale_df <- function(data, is_numeric) {
    .Call('_lloydr_scale_df', PACKAGE = 'lloydr', data, is_numeric)
}

