# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_distance_cpp <- function(point, centroid) {
    .Call(`_lloydr_cosine_distance_cpp`, point, centroid)
}

cosine_point_distances <- function(data) {
    .Call(`_lloydr_cosine_point_distances`, data)
}

euclidean_distance_cpp <- function(point, centroid) {
    .Call(`_lloydr_euclidean_distance_cpp`, point, centroid)
}

euclidean_point_distances <- function(data) {
    .Call(`_lloydr_euclidean_point_distances`, data)
}

gower_distance_cpp <- function(point, centroid, data) {
    .Call(`_lloydr_gower_distance_cpp`, point, centroid, data)
}

manhattan_distance_cpp <- function(point, centroid) {
    .Call(`_lloydr_manhattan_distance_cpp`, point, centroid)
}

manhattan_point_distances <- function(data) {
    .Call(`_lloydr_manhattan_point_distances`, data)
}

scale_data <- function(data) {
    .Call(`_lloydr_scale_data`, data)
}

